# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :mdadm => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
			:dfile => './sata1.vdi',
			:size => 4096,
			:port => 1
		},
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 4096, # Megabytes
			:port => 2
		},
                :sata3 => {
                        :dfile => './sata3.vdi',
                        :size => 4096,
                        :port => 3
                },
                :sata4 => {
                        :dfile => './sata4.vdi',
                        :size => 4096,
                        :port => 4
                }

	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset
          box.vm.synced_folder ".", "/vagrant", disabled: true

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
            SHELL
            box.vm.provision "partitions", after: "shell", type: "shell" do |s|
                s.inline = <<-SHELL
                        for i in {b..e}; do parted -s /dev/sd$i mklabel gpt
                                # make /home
                                parted /dev/sd$i mkpart primary ext4 3GiB 100%
                                # make /var
                                parted /dev/sd$i mkpart primary ext4 2GiB 3GiB;
                                done
                        for i in {b,c}; do
                                # make /boot
                                parted /dev/sd$i mkpart primary ext4 0 50MiB
                                # make /
                                parted /dev/sd$i mkpart primary ext4 50MiB 1GiB;
                                done
                        for i in {d,e}; do
                                # make swap
                                parted /dev/sd$i mkpart primary linux-swap 1GiB 2GiB;
                                done
                SHELL
            end
      end
  end
end


