#!/usr/bin/expect -f
set timeout -1
spawn ./read.sh
expect "Hello, who are you?\r"
send -- "Im Leonid\r"
expect "Can I ask you some questions?\r"
send -- "Sure\r"
expect "What is your favorite topic?\r"
send -- "Linux\r"
expect eof